const BrowserNamesMap = {
  '2345Explorer': '2345Explorer',
  '360 Browser': '360 Browser',
  Amaya: 'Amaya',
  'Android Browser': 'Android Browser',
  Arora: 'Arora',
  Avant: 'Avant',
  Avast: 'Avast',
  AVG: 'AVG',
  BIDUBrowser: 'BIDUBrowser',
  Baidu: 'Baidu',
  Basilisk: 'Basilisk',
  Blazer: 'Blazer',
  Bolt: 'Bolt',
  Brave: 'Brave',
  Bowser: 'Bowser',
  Camino: 'Camino',
  Chimera: 'Chimera',
  'Chrome Headless': 'Chrome Headless',
  'Chrome WebView': 'Chrome WebView',
  Chrome: 'Chrome',
  Chromium: 'Chromium',
  'Comodo Dragon': 'Comodo Dragon',
  Dillo: 'Dillo',
  Dolphin: 'Dolphin',
  Doris: 'Doris',
  Edge: 'Edge',
  Electron: 'Electron',
  Epiphany: 'Epiphany',
  Facebook: 'Facebook',
  Falkon: 'Falkon',
  Fennec: 'Fennec',
  Firebird: 'Firebird',
  'Firefox Reality': 'Firefox Reality',
  Flock: 'Flock',
  Flow: 'Flow',
  GSA: 'GSA',
  GoBrowser: 'GoBrowser',
  'ICE Browser': 'ICE Browser',
  IE: 'IE',
  IEMobile: 'IEMobile',
  IceApe: 'IceApe',
  IceCat: 'IceCat',
  IceDragon: 'IceDragon',
  Iceweasel: 'Iceweasel',
  Instagram: 'Instagram',
  Iridium: 'Iridium',
  Iron: 'Iron',
  Jasmine: 'Jasmine',
  'K-Meleon': 'K-Meleon',
  Kindle: 'Kindle',
  Klar: 'Klar',
  Konqueror: 'Konqueror',
  LBBROWSER: 'LBBROWSER',
  Line: 'Line',
  Links: 'Links',
  Lunascape: 'Lunascape',
  Lynx: 'Lynx',
  'MIUI Browser': 'MIUI Browser',
  'Maemo Browser': 'Maemo Browser',
  Maemo: 'Maemo',
  Maxthon: 'Maxthon',
  'MetaSr Midori': 'MetaSr Midori',
  Minimo: 'Minimo',
  'Mobile Safari': 'Mobile Safari',
  Mosaic: 'Mosaic',
  Mozilla: 'Mozilla',
  NetFront: 'NetFront',
  NetSurf: 'NetSurf',
  Netfront: 'Netfront',
  Netscape: 'Netscape',
  NokiaBrowser: 'NokiaBrowser',
  Obigo: 'Obigo',
  'Oculus Browser': 'Oculus Browser',
  OmniWeb: 'OmniWeb',
  'Opera Coast': 'Opera Coast',
  'Opera Mini': 'Opera Mini',
  'Opera Mobi': 'Opera Mobi',
  'Opera Tablet': 'Opera Tablet',
  PaleMoon: 'PaleMoon',
  PhantomJS: 'PhantomJS',
  Phoenix: 'Phoenix',
  Polaris: 'Polaris',
  Puffin: 'Puffin',
  QQ: 'QQ',
  QQBrowser: 'QQBrowser',
  QQBrowserLite: 'QQBrowserLite',
  Quark: 'Quark',
  QupZilla: 'QupZilla',
  RockMelt: 'RockMelt',
  Safari: 'Safari',
  'Sailfish Browser': 'Sailfish Browser',
  'Samsung Browser': 'Samsung Browser',
  SeaMonkey: 'SeaMonkey',
  Silk: 'Silk',
  Skyfire: 'Skyfire',
  Sleipnir: 'Sleipnir',
  Slim: 'Slim',
  SlimBrowser: 'SlimBrowser',
  Swiftfox: 'Swiftfox',
  Tesla: 'Tesla',
  'Tizen Browser': 'Tizen Browser',
  UCBrowser: 'UCBrowser',
  'UP.Browser': 'UP.Browser',
  Vivaldi: 'Vivaldi',
  Waterfox: 'Waterfox',
  WeChat: 'WeChat',
  Weibo: 'Weibo',
  Yandex: 'Yandex',
  baidu: 'baidu',
  iCab: 'iCab',
  w3m: 'w3m',
  'Whale Browser': 'Whale Browser',
};

const VendorNamesMap = {
  Acer: 'Acer',
  Alcatel: 'Alcatel',
  Amazon: 'Amazon',
  Apple: 'Apple',
  Archos: 'Archos',
  ASUS: 'ASUS',
  'AT&T': 'AT&T',
  BenQ: 'BenQ',
  BlackBerry: 'BlackBerry',
  Dell: 'Dell',
  Essential: 'Essential',
  Fairphone: 'Fairphone',
  GeeksPhone: 'GeeksPhone',
  Google: 'Google',
  HP: 'HP',
  HTC: 'HTC',
  Huawei: 'Huawei',
  Jolla: 'Jolla',
  Lenovo: 'Lenovo',
  LG: 'LG',
  Meizu: 'Meizu',
  Microsoft: 'Microsoft',
  Motorola: 'Motorola',
  Nexian: 'Nexian',
  Nintendo: 'Nintendo',
  Nokia: 'Nokia',
  Nvidia: 'Nvidia',
  OnePlus: 'OnePlus',
  OPPO: 'OPPO',
  Ouya: 'Ouya',
  Palm: 'Palm',
  Panasonic: 'Panasonic',
  Pebble: 'Pebble',
  Polytron: 'Polytron',
  Realme: 'Realme',
  RIM: 'RIM',
  Roku: 'Roku',
  Samsung: 'Samsung',
  Sharp: 'Sharp',
  Siemens: 'Siemens',
  'Sony Ericsson': 'Sony Ericsson',
  Sprint: 'Sprint',
  Tesla: 'Tesla',
  Vivo: 'Vivo',
  Vodafone: 'Vodafone',
  Xbox: 'Xbox',
  Xiaomi: 'Xiaomi',
  Zebra: 'Zebra',
  ZTE: 'ZTE',
};

const EngineNamesMap = {
  Amaya: 'Amaya',
  Blink: 'Blink',
  EdgeHTML: 'EdgeHTML',
  Flow: 'Flow',
  Gecko: 'Gecko',
  Goanna: 'Goanna',
  iCab: 'iCab',
  KHTML: 'KHTML',
  Links: 'Links',
  Lynx: 'Lynx',
  NetFront: 'NetFront',
  NetSurf: 'NetSurf',
  Presto: 'Presto',
  Tasman: 'Tasman',
  Trident: 'Trident',
  w3m: 'w3m',
  WebKit: 'WebKit',
};
const CpuArchMap = {
  '68k': '68k',
  amd64: 'amd64',
  'arm[64/hf]': 'arm[64/hf]',
  avr: 'avr',
  'ia[32/64]': 'ia[32/64]',
  'irix[64]': 'irix[64]',
  'mips[64]': 'mips[64]',
  'pa-risc': 'pa-risc',
  ppc: 'ppc',
  'sparc[64]': 'sparc[64]',
};

const OsNamesMap = {
  AIX: 'AIX',
  'Amiga OS': 'Amiga OS',
  'Android[-x86]': 'Android[-x86]',
  Arch: 'Arch',
  Bada: 'Bada',
  BeOS: 'BeOS',
  BlackBerry: 'BlackBerry',
  CentOS: 'CentOS',
  'Chromium OS': 'Chromium OS',
  Contiki: 'Contiki',
  Fedora: 'Fedora',
  'Firefox OS': 'Firefox OS',
  FreeBSD: 'FreeBSD',
  Debian: 'Debian',
  Deepin: 'Deepin',
  DragonFly: 'DragonFly',
  'elementary OS': 'elementary OS',
  Fuchsia: 'Fuchsia',
  Gentoo: 'Gentoo',
  GhostBSD: 'GhostBSD',
  GNU: 'GNU',
  Haiku: 'Haiku',
  'HP-UX': 'HP-UX',
  Hurd: 'Hurd',
  iOS: 'iOS',
  Joli: 'Joli',
  KaiOS: 'KaiOS',
  Linpus: 'Linpus',
  Linspire: 'Linspire',
  Linux: 'Linux',
  'Mac OS': 'Mac OS',
  Maemo: 'Maemo',
  Mageia: 'Mageia',
  Mandriva: 'Mandriva',
  Manjaro: 'Manjaro',
  MeeGo: 'MeeGo',
  Minix: 'Minix',
  Mint: 'Mint',
  'Morph OS': 'Morph OS',
  NetBSD: 'NetBSD',
  Nintendo: 'Nintendo',
  OpenBSD: 'OpenBSD',
  OpenVMS: 'OpenVMS',
  'OS/2': 'OS/2',
  Palm: 'Palm',
  'PC-BSD': 'PC-BSD',
  PCLinuxOS: 'PCLinuxOS',
  Plan9: 'Plan9',
  PlayStation: 'PlayStation',
  QNX: 'QNX',
  Raspbian: 'Raspbian',
  RedHat: 'RedHat',
  'RIM Tablet OS': 'RIM Tablet OS',
  'RISC OS': 'RISC OS',
  Sabayon: 'Sabayon',
  Sailfish: 'Sailfish',
  Series40: 'Series40',
  Slackware: 'Slackware',
  Solaris: 'Solaris',
  SUSE: 'SUSE',
  Symbian: 'Symbian',
  Tizen: 'Tizen',
  Ubuntu: 'Ubuntu',
  Unix: 'Unix',
  VectorLinux: 'VectorLinux',
  WebOS: 'WebOS',
  'Windows Mobile': 'Windows Mobile',
  'Windows Phone': 'Windows Phone',
  Zenwalk: 'Zenwalk',
};
